import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Language = "en" | "hi";

type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const translations = {
  en: {
    home: "Home", forecast: "Forecast", marketRisk: "Market Risk", bestMandi: "Best Mandi", alerts: "Alerts", account: "Account",
    checking: "Checking", live: "Live", unavailable: "Unavailable", changeLanguage: "Change language", skipToContent: "Skip to market view", backToMarket: "Back to market", farmerAccount: "Farmer account", farmerProfile: "Farmer profile",
    liveMandiIntelligence: "Market guidance", checkCropMarket: "Know the best day and best mandi to sell your crop.", chooseCropMandi: "Choose your crop and mandi to see prices for the next few days, selling advice, and nearby mandi differences.", crop: "Crop", mandi: "Mandi", forecastDays: "Days to check", selectCrop: "Select crop", selectMandi: "Select mandi", checkTodaysMarket: "Check today's market", checkingLiveMarket: "Checking market prices…", loadingChoices: "Loading crops and mandis…", retry: "Try again",
    days: "days", day: "Day", popularCrops: "Popular crops", searchMandi: "Search mandi", searchMandiPlaceholder: "Type a district or mandi name…", noMandiMatches: "No mandi matches found.", p10Floor: "Low price", p50Median: "Expected price", p90Ceiling: "High price", chartExplanation: "The shaded band shows the likely price range. The star marks the best day to sell.", peakDayIs: "Best day to sell is", priceCorridor: "Where today's price sits", expectedGain: "Gain vs today", voiceAdvisory: "Listen to advice", shareWhatsapp: "Share on WhatsApp", sellUrgency: "If supply is rising near you, consider selling in the next day or two.", farmerMandiGuidance: "Compare the extra gain with your travel and transport cost.", liveServiceUnavailable: "Could not load choices", couldNotLoadChoices: "Could not load market choices", liveChoicesUnavailable: "Crop and mandi choices are temporarily unavailable. Please try again.", couldNotLoadChoicesMessage: "We could not load crops and mandis. Please try again.",
    marketDecisionHere: "Your market advice will appear here", selectCropMandiGuidance: "Select your crop and mandi to see prices, forecasts, and selling advice.", checkForecast: "Checking prices and advice", riskMandiContinue: "Risk and mandi checks continue separately.", liveResponse: "Market update", refreshForecast: "Refresh", todaysDecision: "Today's advice", expectedMarketPrice: "Expected price", quintal: "/ quintal", likelyRange: "Likely range", suggestedAction: "What to do", seeLiveGuidance: "See advice", nextDays: "Next", expectedPrice: "Expected price", likelyRangeLegend: "Likely range", forecastPointsMissing: "Price chart unavailable", notEnoughPoints: "We could not draw the price chart for this selection.", marketWarning: "Price alert", noWarningRecords: "No alerts", noRiskWarnings: "No unusual price movement seen for this crop and mandi.", checkingMarketRisk: "Checking price alerts", reviewingMovement: "Reviewing recent price changes.", returnedWarningRecords: "alerts found", recordsAnalyzed: "Days checked", latestMovement: "Recent change", checkingMandiPrices: "Checking other mandis", comparingMarkets: "Comparing nearby mandi prices.", bestMandiLabel: "Better mandi", liveOpportunities: "other mandis found", noOpportunity: "No better mandi found", noBetterOpportunity: "No nearby mandi is paying clearly more for this crop right now.", grossDifference: "extra per quintal", modelDisclaimer: "Guidance only — not a guarantee. Transport and commission costs are not included.",
    stayInformed: "Stay informed", receiveDecision: "Receive your market decision", signInAlerts: "Sign in to save your crop and mandi preferences and receive alerts.", loginOrCreate: "Login or create account", chooseFirst: "Choose a crop and mandi first", alertConnected: "Your alert will be connected to the live market selection.", selectedMarket: "Selected market", channel: "Channel", deliveryTime: "Delivery time", language: "Language", saveAlert: "Save alert", removeAlert: "Remove alert subscription", alertActionFailed: "Alert action failed",
    login: "Login", createAccount: "Create account", useOtp: "Use OTP", fullName: "Full name", mobileNumber: "Mobile number", password: "Password", otpCode: "OTP code", enterName: "Enter your full name", enterMobile: "10-digit mobile number", enterPassword: "Enter your password", enterOtp: "Enter 6-digit OTP", pleaseWait: "Please wait…", createFarmerAccount: "Create farmer account", sendOtp: "Send OTP", verifyOtp: "Verify OTP", farmerAccountReady: "Your farmer account is ready. Return to the market view to continue.", signInToSave: "Sign in to save your preferences and receive live market alerts.", keepDecisionsClose: "Keep your market decisions close.", authenticationFailed: "Authentication could not be completed", accountAccess: "Account access",
    emailAddress: "Email address (Optional)", enterEmail: "farmer@example.com (optional)", loginTab: "Login", signupTab: "Create Account", loginWithOtp: "Login with OTP", loginWithPassword: "Login with Password", signupWithOtp: "Sign up with OTP", signupWithPassword: "Sign up with password", accountNotFoundSignup: "No account found for this mobile number. Please create an account first.", alreadyRegisteredLogin: "An account already exists for this mobile number. Please log in instead.", alreadyHaveAccount: "Already have an account? Login", needAccount: "Don't have an account? Sign up", sendOtpAndRegister: "Verify mobile and create account", registerSuccess: "Account created successfully. You are now logged in.",
    preferences: "Your market preferences.", preferencesIntro: "These preferences are loaded from your account and used to personalize live market decisions.", homeMandi: "Home mandi", preferredCrop: "Preferred crop", savePreferences: "Save preferences", signInProfile: "Sign in to view your profile", loadingProfile: "Loading your profile", profileLoadingMessage: "Requesting your saved preferences from the live service.", couldNotSavePreferences: "Could not save your preferences.", signOut: "Sign out", saveSuccess: "Your preferences were saved.",
    noLiveService: "We could not reach the service.", connectionTryAgain: "Please check your connection and try again.", signedInMessage: "You are signed in. Return to the market view to continue.", accountReadyMessage: "Your farmer account is ready. Return to the market view to continue.", otpRequested: "OTP requested. Enter the code sent to your mobile.", otpSignedIn: "You are signed in with OTP. Return to the market view to continue.", alertsLoading: "Loading your alert subscriptions…", alertsLoadFailed: "Could not load your alert subscriptions.", retryAlerts: "Retry loading alerts", profileRetry: "Retry loading profile", voiceUnavailable: "Voice advice is not supported in this browser.", voiceFailed: "Voice advice could not be started.", trustTransparent: "Clear price range", trustLiveBackend: "Updated market data", trustFarmerFirst: "Easy to understand advice", invalidSelection: "Please choose a valid crop and mandi, then try again.", serviceUnavailable: "This service is temporarily unavailable. Please try again shortly.", serviceTrouble: "Something went wrong. Please try again later.", serviceCouldNotLoad: "We could not load this information for your selection. Please try again.", serviceUnavailableTitle: "Service temporarily unavailable", serviceCouldNotLoadTitle: "Could not load information", chooseCropMandiAlert: "Choose a crop and mandi before saving an alert.", addMobileAlert: "Add a mobile number to your profile before saving an alert.", chooseDeliveryTime: "Choose a delivery time before saving an alert.", enterTelegramChatId: "Enter your Telegram chat ID to enable Telegram alerts.", alertSaved: "Your alert subscription was saved.", alertRemoved: "The alert subscription was removed.", alertSaveFailed: "Could not save the alert subscription.", alertRemoveFailed: "Could not remove the alert subscription.",     chooseCropTitle: "Choose Your Crop & Market", chooseCropDescription: "Select a crop such as Potato, Onion, or Tomato, then choose your nearest mandi.", seePricesTitle: "See Prices for the Next 7 Days", seePricesDescription: "Find out which day prices will be highest so you can plan when to sell.", getAdviceTitle: "Should You Sell Today or Wait?", getAdviceDescription: "Get clear guidance on when to sell and which nearby mandi may offer a better price.",
    onboardingTitle: "Get the Best Price for Your Crop — in 3 Steps", onboardingIntro: "Choose your crop and nearest market above. We'll tell you the best day and the best place to sell.", signupIntro: "Sign up to unlock real-time mandi intelligence, price trajectory forecasts, and personalized profit alerts.", editNumber: "Edit", editDetails: "Edit", showPassword: "Show password", hidePassword: "Hide password", resendOtp: "Resend OTP", resendOtpIn: "Resend OTP in", verifyAndCompleteSignup: "Verify & Complete Signup", telegramChatId: "Telegram chat ID", alertLanguage: "Alert language", confirmRemoveAlert: "Remove this alert subscription?", unusualPriceMovement: "Unusual price movement", warningsFound: "warnings found", recentPriceChange: "Recent price change", bestDay: "Best day", refreshAll: "Refresh",
    whyThisAdvice: "Why this advice?", decisionSell: "Sell today", decisionWait: "Wait", decisionHold: "Wait", decisionProfit: "Good chance",
    actionSellToday: "Sell today", actionWaitFewDays: "Wait a few days", actionGoodChance: "Good chance to earn more",
    gainMoreThanToday: "About {amount} more per quintal than today", gainLessThanToday: "About {amount} less per quintal than today",
    trustHigh: "Strong", trustMedium: "Moderate", trustLow: "Low", trustLabel: "How sure we are",
    priceLow: "Low", priceMid: "Expected", priceHigh: "High", mandiMoreGain: "{amount} more per quintal",
    mobileRisk: "Risk", riskAllClear: "No big price shocks seen", riskWatchOut: "Watch out — prices moving fast",
    mandiOthersPayingMore: "Other mandis paying more", latestMovementPlain: "Price change this week",
    switchToHindi: "Hindi", switchToEnglish: "English", changeLanguageToHindi: "Switch to Hindi", changeLanguageToEnglish: "Switch to English", accountSignedInHint: "Signed in — open account or sign out", brandTagline: "Your market. Your decision.", navMarket: "Market",
    offlineBannerMessage: "Can't connect right now. Check your internet and try again.",
    serviceStatusChecking: "Checking connection to live market data.",
    serviceStatusLive: "Connected. Prices and advice are from live market data.",
    serviceStatusDegraded: "Some services are slow. Advice may load slowly or be incomplete.",
    serviceStatusUnavailable: "Cannot reach the server. Check your internet and try again.",
    topbarOverflowMenu: "More options",
    recentCrops: "Recent", recentMandis: "Recent mandis", allCrops: "All crops",
    changeMarketSelection: "More options", hideMarketOptions: "Fewer options", checkAnotherCrop: "Check another crop",
    transportCost: "Trip cost (optional)", transportCostHint: "Diesel, labour, toll — your full trip cost",
    saleQuintals: "Quintals to sell", saleQuintalsHint: "Used to split trip cost per quintal",
    mandiComparedFrom: "Compared from", mandiExtraPerQuintal: "Extra / quintal", mandiNetPerQuintal: "After trip",
    mandiNetGain: "About {amount} / quintal", mandiNotWorth: "Not worth after trip", mandiWorthTrip: "Best option — about {amount} per quintal after trip",
    mandiNotWorthTrip: "Trip cost is higher than the extra gain at these mandis",
    chartHorizonLabel: "Chart days", chartDays7: "7 days", chartDays14: "14 days",
    chartToday: "Today", chartBestDay: "Best day", chartNeed14Days: "Choose 14 days in more options above, or tap 14 days again to reload.",
    p10Tooltip: "Low end of the likely price range.",
    p50Tooltip: "Most likely expected price.",
    p90Tooltip: "High end of the likely price range.",
    adviceReasonGain: "Expected gain vs today", adviceReasonConfidence: "Confidence", modelVersionLabel: "Model version",
    dataAsOf: "Data as of {datetime}",
    toastOtpSent: "OTP sent to your mobile.", toastLoginSuccess: "Signed in successfully.", toastAlertSaved: "Alert saved.", toastAlertRemoved: "Alert removed.",
    switchTheme: "Switch colour theme", lightMode: "Light", darkMode: "Dark", degraded: "Degraded", signInForRisk: "Sign in to view live supply-shock warnings for this crop and mandi.", signInForMandi: "Sign in to compare nearby mandi prices and see the best selling market.", latestMovementUnit: "₹ / quintal / day", redirectingHome: "Signed in. Taking you to the market view…", passwordRequired: "Please create a password with at least 6 characters.", otpWait: "seconds", singleDayOutlook: "One-day outlook", notFoundTitle: "This page is not available", notFoundMessage: "The page you requested does not exist. Return to the live market view to continue.", goHome: "Go to market view", footerTagline: "Live APMC market intelligence for farmers and traders.", whatsappChannel: "WhatsApp", telegramChannel: "Telegram", bothChannels: "WhatsApp and Telegram", siteNav: "Site", mobileNav: "Mobile", themeGroup: "Appearance", signedInAs: "Signed in",
    onboardingStepLabel: "Step {current} of {total}", onboardingSkip: "Skip", onboardingNext: "Next", onboardingSaveAndGo: "Save and go to market", onboardingMandiTitle: "Where do you usually sell?", onboardingMandiIntro: "Choose your home mandi so we can show nearby prices and travel comparisons.", onboardingCropTitle: "What crop do you grow most?", onboardingCropIntro: "We will use this to pre-fill your market checks and alerts.", onboardingAlertTitle: "Get daily alerts?", onboardingAlertIntro: "Optional — receive your sell-or-wait advice on WhatsApp each morning.", onboardingEnableAlerts: "Send advice on WhatsApp", onboardingAlertOptional: "You can turn alerts on or off anytime from the market page.", onboardingComplete: "Your setup is saved. Checking today's market…",
  },
  hi: {
    home: "होम", forecast: "पूर्वानुमान", marketRisk: "बाज़ार जोखिम", bestMandi: "श्रेष्ठ मंडी", alerts: "अलर्ट", account: "खाता",
    checking: "जाँच जारी", live: "लाइव", unavailable: "उपलब्ध नहीं", changeLanguage: "भाषा बदलें", skipToContent: "बाज़ार दृश्य पर जाएँ", backToMarket: "बाज़ार पर वापस जाएँ", farmerAccount: "किसान खाता", farmerProfile: "किसान प्रोफ़ाइल",
    liveMandiIntelligence: "बाज़ार सलाह", checkCropMarket: "अपनी फसल का सही दिन और सही मंडी जानें।", chooseCropMandi: "अगले कुछ दिनों के भाव, बेचने की सलाह और नज़दीकी मंडियों का अंतर देखने के लिए फसल और मंडी चुनें।", crop: "फसल", mandi: "मंडी", forecastDays: "दिन देखें", selectCrop: "फसल चुनें", selectMandi: "मंडी चुनें", checkTodaysMarket: "आज का बाज़ार देखें", checkingLiveMarket: "बाज़ार भाव जाँच हो रहे हैं…", loadingChoices: "फसलें और मंडियाँ लोड हो रही हैं…", retry: "फिर कोशिश करें",
    days: "दिन", day: "दिन", popularCrops: "लोकप्रिय फसलें", searchMandi: "मंडी खोजें", searchMandiPlaceholder: "जिला या मंडी का नाम लिखें…", noMandiMatches: "कोई मंडी नहीं मिली।", p10Floor: "कम भाव", p50Median: "संभावित भाव", p90Ceiling: "ज़्यादा भाव", chartExplanation: "छायांकित हिस्सा संभावित भाव सीमा दिखाता है। तारा बेचने का सबसे अच्छा दिन दिखाता है।", peakDayIs: "बेचने का सबसे अच्छा दिन", priceCorridor: "आज का भाव कहाँ है", expectedGain: "आज से लाभ", voiceAdvisory: "सलाह सुनें", shareWhatsapp: "व्हाट्सऐप पर भेजें", sellUrgency: "अगर आपके इलाके में आपूर्ति बढ़ रही है, तो एक-दो दिन में बेचने पर विचार करें।", farmerMandiGuidance: "अतिरिक्त लाभ की तुलना यात्रा और परिवहन खर्च से करें।", liveServiceUnavailable: "विकल्प लोड नहीं हो सके", couldNotLoadChoices: "बाज़ार विकल्प लोड नहीं हो सके", liveChoicesUnavailable: "फसल और मंडी विकल्प अस्थायी रूप से उपलब्ध नहीं हैं। कृपया फिर कोशिश करें।", couldNotLoadChoicesMessage: "फसलें और मंडियाँ लोड नहीं हो सकीं। कृपया फिर कोशिश करें।",
    marketDecisionHere: "आपकी बाज़ार सलाह यहाँ दिखेगी", selectCropMandiGuidance: "भाव, पूर्वानुमान और बेचने की सलाह देखने के लिए फसल और मंडी चुनें।", checkForecast: "भाव और सलाह जाँच हो रही है", riskMandiContinue: "जोखिम और मंडी की जाँच अलग से चलती है।", liveResponse: "बाज़ार अपडेट", refreshForecast: "फिर लोड करें", todaysDecision: "आज की सलाह", expectedMarketPrice: "संभावित भाव", quintal: "/ क्विंटल", likelyRange: "संभावित सीमा", suggestedAction: "क्या करें", seeLiveGuidance: "सलाह देखें", nextDays: "अगले", expectedPrice: "संभावित भाव", likelyRangeLegend: "संभावित सीमा", forecastPointsMissing: "भाव चार्ट उपलब्ध नहीं", notEnoughPoints: "इस चयन के लिए भाव चार्ट नहीं बना सका।", marketWarning: "भाव चेतावनी", noWarningRecords: "कोई चेतावनी नहीं", noRiskWarnings: "इस फसल और मंडी में असामान्य भाव बदलाव नहीं दिखा।", checkingMarketRisk: "भाव चेतावनी जाँच हो रही है", reviewingMovement: "हाल के भाव बदलाव देखे जा रहे हैं।", returnedWarningRecords: "चेतावनियाँ मिलीं", recordsAnalyzed: "दिन जाँचे गए", latestMovement: "हाल का बदलाव", checkingMandiPrices: "दूसरी मंडियाँ देखी जा रही हैं", comparingMarkets: "नज़दीकी मंडी भावों की तुलना हो रही है।", bestMandiLabel: "बेहतर मंडी", liveOpportunities: "दूसरी मंडियाँ मिलीं", noOpportunity: "कोई बेहतर मंडी नहीं मिली", noBetterOpportunity: "अभी कोई नज़दीकी मंडी इस फसल के लिए साफ़ तौर पर ज़्यादा भाव नहीं दे रही।", grossDifference: "प्रति क्विंटल अतिरिक्त", modelDisclaimer: "केवल मार्गदर्शन — गारंटी नहीं। परिवहन और कमीशन खर्च शामिल नहीं हो सकते।",
    stayInformed: "जानकारी रखें", receiveDecision: "अपना बाज़ार निर्णय पाएँ", signInAlerts: "अपनी फसल और मंडी प्राथमिकताएँ सहेजने और अलर्ट पाने के लिए साइन इन करें।", loginOrCreate: "लॉगिन या खाता बनाएँ", chooseFirst: "पहले फसल और मंडी चुनें", alertConnected: "आपका अलर्ट लाइव बाज़ार चयन से जुड़ा होगा।", selectedMarket: "चयनित बाज़ार", channel: "माध्यम", deliveryTime: "समय", language: "भाषा", saveAlert: "अलर्ट सहेजें", removeAlert: "अलर्ट सदस्यता हटाएँ", alertActionFailed: "अलर्ट कार्रवाई विफल",
    login: "लॉगिन", createAccount: "खाता बनाएँ", useOtp: "OTP इस्तेमाल करें", fullName: "पूरा नाम", mobileNumber: "मोबाइल नंबर", password: "पासवर्ड", otpCode: "OTP कोड", enterName: "अपना पूरा नाम दर्ज करें", enterMobile: "10 अंकों का मोबाइल नंबर", enterPassword: "अपना पासवर्ड दर्ज करें", enterOtp: "6 अंकों का OTP दर्ज करें", pleaseWait: "कृपया प्रतीक्षा करें…", createFarmerAccount: "किसान खाता बनाएँ", sendOtp: "OTP भेजें", verifyOtp: "OTP सत्यापित करें", farmerAccountReady: "आपका किसान खाता तैयार है। आगे बढ़ने के लिए बाज़ार दृश्य पर लौटें।", signInToSave: "प्राथमिकताएँ सहेजने और लाइव बाज़ार अलर्ट पाने के लिए साइन इन करें।", keepDecisionsClose: "अपने बाज़ार निर्णय पास रखें।", authenticationFailed: "प्रमाणीकरण पूरा नहीं हो सका", accountAccess: "खाता पहुँच",
    emailAddress: "ईमेल पता (वैकल्पिक)", enterEmail: "ईमेल पता (वैकल्पिक)", loginTab: "लॉगिन", signupTab: "नया खाता बनाएँ", loginWithOtp: "OTP से लॉगिन करें", loginWithPassword: "पासवर्ड से लॉगिन करें", signupWithOtp: "OTP से खाता बनाएँ", signupWithPassword: "पासवर्ड से खाता बनाएँ", accountNotFoundSignup: "इस मोबाइल नंबर पर कोई खाता नहीं मिला। कृपया पहले खाता बनाएँ।", alreadyRegisteredLogin: "इस मोबाइल नंबर पर पहले से खाता है। कृपया लॉगिन करें।", alreadyHaveAccount: "पहले से खाता है? लॉगिन करें", needAccount: "खाता नहीं है? नया खाता बनाएँ", sendOtpAndRegister: "मोबाइल सत्यापित करें और खाता बनाएँ", registerSuccess: "खाता सफलतापूर्वक बन गया। आप लॉगिन हो चुके हैं।",
    preferences: "आपकी बाज़ार प्राथमिकताएँ।", preferencesIntro: "ये प्राथमिकताएँ आपके खाते से ली गई हैं और लाइव बाज़ार निर्णय को आपके अनुसार बनाती हैं।", homeMandi: "मुख्य मंडी", preferredCrop: "पसंदीदा फसल", savePreferences: "प्राथमिकताएँ सहेजें", signInProfile: "प्रोफ़ाइल देखने के लिए साइन इन करें", loadingProfile: "प्रोफ़ाइल लोड हो रही है", profileLoadingMessage: "लाइव सेवा से आपकी सहेजी प्राथमिकताएँ ली जा रही हैं।", couldNotSavePreferences: "आपकी प्राथमिकताएँ सहेजी नहीं जा सकीं।", signOut: "साइन आउट", saveSuccess: "आपकी प्राथमिकताएँ सहेज दी गई हैं।",
    noLiveService: "सेवा तक पहुँचा नहीं जा सका।", connectionTryAgain: "कृपया कनेक्शन जाँचकर फिर कोशिश करें।", signedInMessage: "आप साइन इन हैं। जारी रखने के लिए बाज़ार दृश्य पर लौटें।", accountReadyMessage: "आपका किसान खाता तैयार है। आगे बढ़ने के लिए बाज़ार दृश्य पर लौटें।", otpRequested: "OTP का अनुरोध किया गया। अपने मोबाइल पर भेजा गया कोड दर्ज करें।", otpSignedIn: "आप OTP से साइन इन हैं। जारी रखने के लिए बाज़ार दृश्य पर लौटें।", alertsLoading: "आपकी अलर्ट सदस्यताएँ लोड हो रही हैं…", alertsLoadFailed: "आपकी अलर्ट सदस्यताएँ लोड नहीं हो सकीं।", retryAlerts: "अलर्ट फिर लोड करें", profileRetry: "प्रोफ़ाइल फिर लोड करें", voiceUnavailable: "इस ब्राउज़र में आवाज़ वाली सलाह उपलब्ध नहीं है।", voiceFailed: "आवाज़ वाली सलाह शुरू नहीं हो सकी।", trustTransparent: "साफ़ भाव सीमा", trustLiveBackend: "ताज़ा बाज़ार जानकारी", trustFarmerFirst: "आसान समझ में सलाह", invalidSelection: "कृपया सही फसल और मंडी चुनकर फिर कोशिश करें।", serviceUnavailable: "यह सेवा अस्थायी रूप से उपलब्ध नहीं है। कृपया थोड़ी देर बाद फिर कोशिश करें।", serviceTrouble: "कुछ गड़बड़ हो गई। कृपया बाद में फिर कोशिश करें।", serviceCouldNotLoad: "आपके चयन के लिए यह जानकारी लोड नहीं हो सकी। कृपया फिर कोशिश करें।", serviceUnavailableTitle: "सेवा अस्थायी रूप से उपलब्ध नहीं", serviceCouldNotLoadTitle: "जानकारी लोड नहीं हो सकी", chooseCropMandiAlert: "अलर्ट सहेजने से पहले फसल और मंडी चुनें।", addMobileAlert: "अलर्ट सहेजने से पहले अपनी प्रोफ़ाइल में मोबाइल नंबर जोड़ें।", chooseDeliveryTime: "अलर्ट का समय चुनें।", enterTelegramChatId: "Telegram अलर्ट चालू करने के लिए chat ID दर्ज करें।", alertSaved: "आपकी अलर्ट सदस्यता सहेज दी गई है।", alertRemoved: "अलर्ट सदस्यता हटा दी गई है।", alertSaveFailed: "अलर्ट सदस्यता सहेजी नहीं जा सकी।", alertRemoveFailed: "अलर्ट सदस्यता हटाई नहीं जा सकी।",     chooseCropTitle: "फसल और मंडी चुनें", chooseCropDescription: "आलू, प्याज या टमाटर जैसी फसल चुनें और अपनी नज़दीकी मंडी चुनें।", seePricesTitle: "अगले 7 दिन के भाव देखें", seePricesDescription: "जानें किस दिन भाव सबसे अधिक रहेगा ताकि आप बेचने का समय तय कर सकें।", getAdviceTitle: "आज बेचें या रुकें?", getAdviceDescription: "बेचने का सही समय और बेहतर भाव देने वाली नज़दीकी मंडी की स्पष्ट सलाह पाएँ।",
    onboardingTitle: "3 आसान कदमों में अपनी फसल का सबसे अच्छा भाव पाएँ", onboardingIntro: "ऊपर अपनी फसल और नज़दीकी मंडी चुनें — हम आपको बताएँगे कि कब और कहाँ बेचना सबसे फायदेमंद है।", signupIntro: "लाइव मंडी भाव, मूल्य पूर्वानुमान और व्यक्तिगत अलर्ट पाने के लिए पंजीकरण करें।", editNumber: "नंबर बदलें", editDetails: "बदलें", showPassword: "पासवर्ड दिखाएँ", hidePassword: "पासवर्ड छिपाएँ", resendOtp: "OTP फिर भेजें", resendOtpIn: "OTP फिर भेजें", verifyAndCompleteSignup: "सत्यापित करें और खाता बनाएँ", telegramChatId: "Telegram चैट ID", alertLanguage: "अलर्ट भाषा", confirmRemoveAlert: "क्या आप यह अलर्ट सदस्यता हटाना चाहते हैं?", unusualPriceMovement: "असामान्य भाव बदलाव", warningsFound: "चेतावनियाँ मिलीं", recentPriceChange: "हाल का भाव बदलाव", bestDay: "सबसे अच्छा दिन", refreshAll: "फिर लोड करें",
    whyThisAdvice: "यह सलाह क्यों?", decisionSell: "आज बेचें", decisionWait: "रुकें", decisionHold: "रुकें", decisionProfit: "अच्छा मौका",
    actionSellToday: "आज ही बेचें", actionWaitFewDays: "कुछ दिन और रुकें", actionGoodChance: "अच्छा मौका है",
    gainMoreThanToday: "आज से लगभग {amount} ज़्यादा प्रति क्विंटल", gainLessThanToday: "आज से लगभग {amount} कम प्रति क्विंटल",
    trustHigh: "अच्छी", trustMedium: "औसत", trustLow: "कम", trustLabel: "हम कितने आश्वस्त हैं",
    priceLow: "कम", priceMid: "संभावित", priceHigh: "ज़्यादा", mandiMoreGain: "प्रति क्विंटल {amount} ज़्यादा",
    mobileRisk: "जोखिम", riskAllClear: "कोई बड़ा भाव झटका नहीं दिखा", riskWatchOut: "सावधान — भाव तेज़ी से बदल रहे हैं",
    mandiOthersPayingMore: "दूसरी मंडियों में ज़्यादा भाव", latestMovementPlain: "इस हफ़्ते भाव में बदलाव",
    switchToHindi: "हिन्दी", switchToEnglish: "अंग्रेज़ी", changeLanguageToHindi: "हिन्दी में बदलें", changeLanguageToEnglish: "अंग्रेज़ी में बदलें", accountSignedInHint: "साइन इन हैं — खाता खोलें या साइन आउट करें", brandTagline: "आपका बाज़ार। आपका फ़ैसला।", navMarket: "बाज़ार",
    offlineBannerMessage: "अभी कनेक्ट नहीं हो पा रहा। इंटरनेट जाँचकर फिर कोशिश करें।",
    serviceStatusChecking: "लाइव बाज़ार डेटा से कनेक्शन जाँच हो रहा है।",
    serviceStatusLive: "कनेक्टेड। भाव और सलाह लाइव बाज़ार डेटा से आ रहे हैं।",
    serviceStatusDegraded: "कुछ सेवाएँ धीमी हैं। सलाह देर से या अधूरी लोड हो सकती है।",
    serviceStatusUnavailable: "सर्वर तक नहीं पहुँच पा रहे। इंटरनेट जाँचकर फिर कोशिश करें।",
    topbarOverflowMenu: "और विकल्प",
    recentCrops: "हाल की", recentMandis: "हाल की मंडियाँ", allCrops: "सभी फसलें",
    changeMarketSelection: "और विकल्प", hideMarketOptions: "कम विकल्प", checkAnotherCrop: "दूसरी फसल देखें",
    transportCost: "यात्रा खर्च (वैकल्पिक)", transportCostHint: "डीज़ल, मज़दूरी, टोल — पूरी यात्रा का खर्च",
    saleQuintals: "बेचने के क्विंटल", saleQuintalsHint: "यात्रा खर्च प्रति क्विंटल बाँटने के लिए",
    mandiComparedFrom: "तुलना यहाँ से", mandiExtraPerQuintal: "अतिरिक्त / क्विंटल", mandiNetPerQuintal: "यात्रा के बाद",
    mandiNetGain: "लगभग {amount} / क्विंटल", mandiNotWorth: "यात्रा के बाद फायदा नहीं", mandiWorthTrip: "सबसे अच्छा विकल्प — यात्रा के बाद लगभग {amount} प्रति क्विंटल",
    mandiNotWorthTrip: "इन मंडियों में अतिरिक्त भाव यात्रा खर्च से कम है",
    chartHorizonLabel: "चार्ट के दिन", chartDays7: "7 दिन", chartDays14: "14 दिन",
    chartToday: "आज", chartBestDay: "सबसे अच्छा दिन", chartNeed14Days: "ऊपर और विकल्प में 14 दिन चुनें, या 14 दिन फिर दबाकर फिर लोड करें।",
    p10Tooltip: "संभावित भाव सीमा का निचला हिस्सा।",
    p50Tooltip: "सबसे संभावित भाव।",
    p90Tooltip: "संभावित भाव सीमा का ऊपरी हिस्सा।",
    adviceReasonGain: "आज की तुलना में अनुमानित लाभ", adviceReasonConfidence: "विश्वास स्तर", modelVersionLabel: "मॉडल संस्करण",
    dataAsOf: "डेटा की तारीख {datetime}",
    toastOtpSent: "OTP आपके मोबाइल पर भेजा गया।", toastLoginSuccess: "सफलतापूर्वक साइन इन हो गए।", toastAlertSaved: "अलर्ट सहेजा गया।", toastAlertRemoved: "अलर्ट हटाया गया।",
    switchTheme: "रंग थीम बदलें", lightMode: "हल्की", darkMode: "गहरी", degraded: "सीमित", signInForRisk: "इस फसल और मंडी के लाइव आपूर्ति-जोखिम चेतावनियाँ देखने के लिए साइन इन करें।", signInForMandi: "नज़दीकी मंडी कीमतों की तुलना और श्रेष्ठ बिक्री बाज़ार देखने के लिए साइन इन करें।", latestMovementUnit: "₹ / क्विंटल / दिन", redirectingHome: "आप साइन इन हैं। बाज़ार दृश्य पर ले जाया जा रहा है…", passwordRequired: "कृपया कम से कम 6 अक्षरों का पासवर्ड बनाएँ।", otpWait: "सेकंड", singleDayOutlook: "एक दिन का अनुमान", notFoundTitle: "यह पृष्ठ उपलब्ध नहीं है", notFoundMessage: "जिस पृष्ठ को आप ढूँढ रहे हैं वह मौजूद नहीं है। जारी रखने के लिए लाइव बाज़ार दृश्य पर लौटें।", goHome: "बाज़ार दृश्य पर जाएँ", footerTagline: "किसानों और व्यापारियों के लिए लाइव APMC बाज़ार जानकारी।", whatsappChannel: "WhatsApp", telegramChannel: "Telegram", bothChannels: "WhatsApp और Telegram", siteNav: "साइट", mobileNav: "मोबाइल", themeGroup: "दिखावट", signedInAs: "साइन इन",
    onboardingStepLabel: "चरण {current} / {total}", onboardingSkip: "छोड़ें", onboardingNext: "आगे", onboardingSaveAndGo: "सहेजें और बाज़ार देखें", onboardingMandiTitle: "आप आमतौर पर कहाँ बेचते हैं?", onboardingMandiIntro: "अपनी मुख्य मंडी चुनें ताकि हम नज़दीकी भाव और यात्रा तुलना दिखा सकें।", onboardingCropTitle: "आप ज़्यादातर कौन सी फसल उगाते हैं?", onboardingCropIntro: "इससे बाज़ार जाँच और अलर्ट में आपकी फसल पहले से भर जाएगी।", onboardingAlertTitle: "रोज़ाना अलर्ट चाहिए?", onboardingAlertIntro: "वैकल्पिक — हर सुबह WhatsApp पर बेचें या रुकें की सलाह पाएँ।", onboardingEnableAlerts: "WhatsApp पर सलाह भेजें", onboardingAlertOptional: "आप कभी भी बाज़ार पृष्ठ से अलर्ट चालू या बंद कर सकते हैं।", onboardingComplete: "आपकी सेटिंग सहेज दी गई। आज का बाज़ार जाँच रहे हैं…",
  },
} as const;

const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = "croplens_language";

export function LanguageProvider({ children, initialLanguage }: { children: ReactNode; initialLanguage?: Language }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (initialLanguage) return initialLanguage;
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored === "hi" ? "hi" : "en";
  });

  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(STORAGE_KEY, next);
  }, []);

  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
