import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Language = "en" | "hi";

type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const translations = {
  en: {
    home: "Home", forecast: "Forecast", marketRisk: "Market Risk", bestMandi: "Best Mandi", alerts: "Alerts", account: "Account",
    checking: "Checking", live: "Live", unavailable: "Unavailable", changeLanguage: "Change language", skipToContent: "Skip to market view", backToMarket: "Back to market", farmerAccount: "Farmer account", farmerProfile: "Farmer profile",
    liveMandiIntelligence: "Live mandi intelligence", checkCropMarket: "Know the Best Day & Best Mandi to Sell Your Crop.", chooseCropMandi: "Choose your crop and mandi to view real-time price confidence corridors, selling advice, and nearby market price differences.", crop: "Crop", mandi: "Mandi", forecastDays: "Forecast days", selectCrop: "Select crop", selectMandi: "Select mandi", checkTodaysMarket: "Check Today’s Market", checkingLiveMarket: "Checking live market…", loadingChoices: "Loading live crop and mandi choices…", retry: "Try again",
    days: "days", day: "Day", popularCrops: "Popular crops", searchMandi: "Search mandi", searchMandiPlaceholder: "Type a district or mandi name…", noMandiMatches: "No mandi matches found.", p10Floor: "P10 floor", p50Median: "P50 median", p90Ceiling: "P90 ceiling", chartExplanation: "The shaded area shows the likely price range. The star marks the highest projected day.", peakDayIs: "Highest projected price day is", priceCorridor: "Current price position", expectedGain: "Expected gain", voiceAdvisory: "Listen to advisory", shareWhatsapp: "Share on WhatsApp", sellUrgency: "Sell within 24–48 hours if local supply is rising.", farmerMandiGuidance: "Compare the expected gain with your travel and transport cost.", liveServiceUnavailable: "Live service unavailable", couldNotLoadChoices: "Could not load market choices", liveChoicesUnavailable: "Live crop and mandi choices are temporarily unavailable. Please try again.", couldNotLoadChoicesMessage: "We could not load the live crop and mandi choices. Please try again.",
    marketDecisionHere: "Your live market decision will appear here", selectCropMandiGuidance: "Select your crop and mandi to view real-time prices, forecasts, and market guidance.", checkForecast: "Checking the live forecast", riskMandiContinue: "Your risk and mandi checks continue independently.", liveResponse: "Live response", refreshForecast: "Refresh forecast", todaysDecision: "Today’s market decision", expectedMarketPrice: "Expected market price", quintal: "/ quintal", likelyRange: "Likely range", suggestedAction: "Suggested action", seeLiveGuidance: "See live guidance", nextDays: "Next", expectedPrice: "Expected price", likelyRangeLegend: "Likely range", forecastPointsMissing: "Forecast points were not returned", notEnoughPoints: "The live service did not provide enough points to draw the forecast.", marketWarning: "Market warning", noWarningRecords: "No warning records returned", noRiskWarnings: "No supply-risk warnings were returned for this selection.", checkingMarketRisk: "Checking market risk", reviewingMovement: "Reviewing recent supply and price movement.", returnedWarningRecords: "returned warning records", recordsAnalyzed: "Records analyzed", latestMovement: "Latest movement", checkingMandiPrices: "Checking mandi prices", comparingMarkets: "Comparing live destination-market information.", bestMandiLabel: "Best mandi", liveOpportunities: "live opportunities returned", noOpportunity: "No opportunity returned", noBetterOpportunity: "No better mandi opportunity was returned for this selection.", grossDifference: "gross difference", modelDisclaimer: "Model-supported guidance, not a guarantee. Costs such as transport and commission may not be included.",
    stayInformed: "Stay informed", receiveDecision: "Receive your market decision", signInAlerts: "Sign in to save your crop and mandi preferences and receive alerts.", loginOrCreate: "Login or create account", chooseFirst: "Choose a crop and mandi first", alertConnected: "Your alert will be connected to the live market selection.", selectedMarket: "Selected market", channel: "Channel", deliveryTime: "Delivery time", language: "Language", saveAlert: "Save alert", removeAlert: "Remove alert subscription", alertActionFailed: "Alert action failed",
    login: "Login", createAccount: "Create account", useOtp: "Use OTP", fullName: "Full name", mobileNumber: "Mobile number", password: "Password", otpCode: "OTP code", enterName: "Enter your full name", enterMobile: "10-digit mobile number", enterPassword: "Enter your password", enterOtp: "Enter 6-digit OTP", pleaseWait: "Please wait…", createFarmerAccount: "Create farmer account", sendOtp: "Send OTP", verifyOtp: "Verify OTP", farmerAccountReady: "Your farmer account is ready. Return to the market view to continue.", signInToSave: "Sign in to save your preferences and receive live market alerts.", keepDecisionsClose: "Keep your market decisions close.", authenticationFailed: "Authentication could not be completed", accountAccess: "Account access",
    emailAddress: "Email address (Optional)", enterEmail: "farmer@example.com (optional)", loginTab: "Login", signupTab: "Create Account", loginWithOtp: "Login with OTP", loginWithPassword: "Login with Password", alreadyHaveAccount: "Already have an account? Login", needAccount: "Don't have an account? Sign up", sendOtpAndRegister: "Verify Mobile & Register", registerSuccess: "Account created successfully. You are now logged in.",
    preferences: "Your market preferences.", preferencesIntro: "These preferences are loaded from your account and used to personalize live market decisions.", homeMandi: "Home mandi", preferredCrop: "Preferred crop", savePreferences: "Save preferences", signInProfile: "Sign in to view your profile", loadingProfile: "Loading your profile", profileLoadingMessage: "Requesting your saved preferences from the live service.", couldNotSavePreferences: "Could not save your preferences.", signOut: "Sign out", saveSuccess: "Your preferences were saved.",
    noLiveService: "The live service could not be reached.", connectionTryAgain: "Please check your connection and try again.", signedInMessage: "You are signed in. Return to the market view to continue.", accountReadyMessage: "Your farmer account is ready. Return to the market view to continue.", otpRequested: "OTP requested. Enter the code sent to your mobile.", otpSignedIn: "You are signed in with OTP. Return to the market view to continue.", alertsLoading: "Loading your alert subscriptions…", alertsLoadFailed: "Could not load your alert subscriptions.", retryAlerts: "Retry loading alerts", profileRetry: "Retry loading profile", voiceUnavailable: "Voice advisory is not supported in this browser.", voiceFailed: "Voice advisory could not be started.", trustTransparent: "Transparent price ranges", trustLiveBackend: "Live backend data", trustFarmerFirst: "Farmer-first guidance", invalidSelection: "Please choose a valid crop and mandi, then try again.", serviceUnavailable: "This live service is temporarily unavailable. Please try again shortly.", serviceTrouble: "The live service is having trouble. Please try again later.", serviceCouldNotLoad: "We could not load this information for your selection. Please try again.", serviceUnavailableTitle: "Live service temporarily unavailable", serviceCouldNotLoadTitle: "Could not load live information", chooseCropMandiAlert: "Choose a crop and mandi before saving an alert.", addMobileAlert: "Add a mobile number to your profile before saving an alert.", chooseDeliveryTime: "Choose a delivery time before saving an alert.", enterTelegramChatId: "Enter your Telegram chat ID to enable Telegram alerts.", alertSaved: "Your alert subscription was saved.", alertRemoved: "The alert subscription was removed.", alertSaveFailed: "Could not save the alert subscription.", alertRemoveFailed: "Could not remove the alert subscription.",     chooseCropTitle: "Choose Your Crop & Market", chooseCropDescription: "Select a crop such as Potato, Onion, or Tomato, then choose your nearest mandi.", seePricesTitle: "See Prices for the Next 7 Days", seePricesDescription: "Find out which day prices will be highest so you can plan when to sell.", getAdviceTitle: "Should You Sell Today or Wait?", getAdviceDescription: "Get clear guidance on when to sell and which nearby mandi may offer a better price.",
    onboardingTitle: "Get the Best Price for Your Crop — in 3 Steps", onboardingIntro: "Choose your crop and nearest market above. We'll tell you the best day and the best place to sell.", signupIntro: "Sign up to unlock real-time mandi intelligence, price trajectory forecasts, and personalized profit alerts.", editNumber: "Edit", editDetails: "Edit", showPassword: "Show password", hidePassword: "Hide password", resendOtp: "Resend OTP", resendOtpIn: "Resend OTP in", verifyAndCompleteSignup: "Verify & Complete Signup", telegramChatId: "Telegram chat ID", alertLanguage: "Alert language", confirmRemoveAlert: "Remove this alert subscription?", unusualPriceMovement: "Unusual price movement", warningsFound: "warnings found", recentPriceChange: "Recent price change", bestDay: "Best day", refreshAll: "Refresh",
    switchTheme: "Switch colour theme", lightMode: "Light", darkMode: "Dark", degraded: "Degraded", signInForRisk: "Sign in to view live supply-shock warnings for this crop and mandi.", signInForMandi: "Sign in to compare nearby mandi prices and see the best selling market.", latestMovementUnit: "₹ / quintal / day", redirectingHome: "Signed in. Taking you to the market view…", passwordRequired: "Please create a password with at least 6 characters.", otpWait: "seconds", singleDayOutlook: "One-day outlook", notFoundTitle: "This page is not available", notFoundMessage: "The page you requested does not exist. Return to the live market view to continue.", goHome: "Go to market view", footerTagline: "Live APMC market intelligence for farmers and traders.", whatsappChannel: "WhatsApp", telegramChannel: "Telegram", bothChannels: "WhatsApp and Telegram", siteNav: "Site", mobileNav: "Mobile", themeGroup: "Appearance", signedInAs: "Signed in",
  },
  hi: {
    home: "होम", forecast: "पूर्वानुमान", marketRisk: "बाज़ार जोखिम", bestMandi: "श्रेष्ठ मंडी", alerts: "अलर्ट", account: "खाता",
    checking: "जाँच जारी", live: "लाइव", unavailable: "उपलब्ध नहीं", changeLanguage: "भाषा बदलें", skipToContent: "बाज़ार दृश्य पर जाएँ", backToMarket: "बाज़ार पर वापस जाएँ", farmerAccount: "किसान खाता", farmerProfile: "किसान प्रोफ़ाइल",
    liveMandiIntelligence: "लाइव मंडी जानकारी", checkCropMarket: "अपनी फसल का सही दाम और सही मंडी जानें।", chooseCropMandi: "वास्तविक कीमत, 7-दिवसीय मूल्य रुझान और श्रेष्ठ मंडी के अंतर देखने के लिए फसल और मंडी चुनें।", crop: "फसल", mandi: "मंडी", forecastDays: "पूर्वानुमान के दिन", selectCrop: "फसल चुनें", selectMandi: "मंडी चुनें", checkTodaysMarket: "आज का बाज़ार देखें", checkingLiveMarket: "लाइव बाज़ार की जाँच हो रही है…", loadingChoices: "लाइव फसल और मंडी विकल्प लोड हो रहे हैं…", retry: "फिर कोशिश करें",
    days: "दिन", day: "दिन", popularCrops: "लोकप्रिय फसलें", searchMandi: "मंडी खोजें", searchMandiPlaceholder: "जिला या मंडी का नाम लिखें…", noMandiMatches: "कोई मंडी नहीं मिली।", p10Floor: "P10 न्यूनतम", p50Median: "P50 अनुमान", p90Ceiling: "P90 अधिकतम", chartExplanation: "छायांकित भाग संभावित कीमत सीमा दिखाता है। तारा सबसे अधिक अनुमानित कीमत वाले दिन को दिखाता है।", peakDayIs: "सबसे अधिक अनुमानित कीमत का दिन", priceCorridor: "वर्तमान कीमत की स्थिति", expectedGain: "अनुमानित लाभ", voiceAdvisory: "सलाह सुनें", shareWhatsapp: "WhatsApp पर साझा करें", sellUrgency: "यदि स्थानीय आपूर्ति बढ़ रही है तो 24–48 घंटे में बेचने पर विचार करें।", farmerMandiGuidance: "अनुमानित लाभ की तुलना यात्रा और परिवहन लागत से करें।", liveServiceUnavailable: "लाइव सेवा उपलब्ध नहीं", couldNotLoadChoices: "बाज़ार विकल्प लोड नहीं हो सके", liveChoicesUnavailable: "लाइव फसल और मंडी विकल्प अस्थायी रूप से उपलब्ध नहीं हैं। कृपया फिर कोशिश करें।", couldNotLoadChoicesMessage: "लाइव फसल और मंडी विकल्प लोड नहीं हो सके। कृपया फिर कोशिश करें।",
    marketDecisionHere: "आपका लाइव बाज़ार निर्णय यहाँ दिखाई देगा", selectCropMandiGuidance: "वास्तविक कीमत, पूर्वानुमान और बाज़ार सलाह देखने के लिए फसल और मंडी चुनें।", checkForecast: "लाइव पूर्वानुमान की जाँच हो रही है", riskMandiContinue: "जोखिम और मंडी की जाँच स्वतंत्र रूप से जारी है।", liveResponse: "लाइव परिणाम", refreshForecast: "पूर्वानुमान फिर लोड करें", todaysDecision: "आज का बाज़ार निर्णय", expectedMarketPrice: "अनुमानित बाज़ार कीमत", quintal: "/ क्विंटल", likelyRange: "संभावित सीमा", suggestedAction: "सुझाई गई कार्रवाई", seeLiveGuidance: "लाइव सलाह देखें", nextDays: "अगले", expectedPrice: "अनुमानित कीमत", likelyRangeLegend: "संभावित सीमा", forecastPointsMissing: "पूर्वानुमान बिंदु नहीं मिले", notEnoughPoints: "लाइव सेवा ने चार्ट बनाने के लिए पर्याप्त बिंदु नहीं दिए।", marketWarning: "बाज़ार चेतावनी", noWarningRecords: "कोई चेतावनी रिकॉर्ड नहीं मिला", noRiskWarnings: "इस चयन के लिए आपूर्ति जोखिम की कोई चेतावनी नहीं मिली।", checkingMarketRisk: "बाज़ार जोखिम की जाँच हो रही है", reviewingMovement: "हाल की आपूर्ति और कीमतों की गतिविधि की समीक्षा हो रही है।", returnedWarningRecords: "चेतावनी रिकॉर्ड मिले", recordsAnalyzed: "रिकॉर्ड का विश्लेषण", latestMovement: "नवीनतम बदलाव", checkingMandiPrices: "मंडी कीमतों की जाँच हो रही है", comparingMarkets: "लाइव गंतव्य मंडी की जानकारी की तुलना हो रही है।", bestMandiLabel: "श्रेष्ठ मंडी", liveOpportunities: "लाइव अवसर मिले", noOpportunity: "कोई अवसर नहीं मिला", noBetterOpportunity: "इस चयन के लिए बेहतर मंडी अवसर नहीं मिला।", grossDifference: "कुल अंतर", modelDisclaimer: "मॉडल आधारित सलाह, गारंटी नहीं। परिवहन और कमीशन की लागत शामिल नहीं हो सकती।",
    stayInformed: "जानकारी रखें", receiveDecision: "अपना बाज़ार निर्णय पाएँ", signInAlerts: "अपनी फसल और मंडी प्राथमिकताएँ सहेजने और अलर्ट पाने के लिए साइन इन करें।", loginOrCreate: "लॉगिन या खाता बनाएँ", chooseFirst: "पहले फसल और मंडी चुनें", alertConnected: "आपका अलर्ट लाइव बाज़ार चयन से जुड़ा होगा।", selectedMarket: "चयनित बाज़ार", channel: "माध्यम", deliveryTime: "समय", language: "भाषा", saveAlert: "अलर्ट सहेजें", removeAlert: "अलर्ट सदस्यता हटाएँ", alertActionFailed: "अलर्ट कार्रवाई विफल",
    login: "लॉगिन", createAccount: "खाता बनाएँ", useOtp: "OTP इस्तेमाल करें", fullName: "पूरा नाम", mobileNumber: "मोबाइल नंबर", password: "पासवर्ड", otpCode: "OTP कोड", enterName: "अपना पूरा नाम दर्ज करें", enterMobile: "10 अंकों का मोबाइल नंबर", enterPassword: "अपना पासवर्ड दर्ज करें", enterOtp: "6 अंकों का OTP दर्ज करें", pleaseWait: "कृपया प्रतीक्षा करें…", createFarmerAccount: "किसान खाता बनाएँ", sendOtp: "OTP भेजें", verifyOtp: "OTP सत्यापित करें", farmerAccountReady: "आपका किसान खाता तैयार है। आगे बढ़ने के लिए बाज़ार दृश्य पर लौटें।", signInToSave: "प्राथमिकताएँ सहेजने और लाइव बाज़ार अलर्ट पाने के लिए साइन इन करें।", keepDecisionsClose: "अपने बाज़ार निर्णय पास रखें।", authenticationFailed: "प्रमाणीकरण पूरा नहीं हो सका", accountAccess: "खाता पहुँच",
    emailAddress: "ईमेल पता (वैकल्पिक)", enterEmail: "ईमेल पता (वैकल्पिक)", loginTab: "लॉगिन", signupTab: "नया खाता बनाएँ", loginWithOtp: "OTP से लॉगिन करें", loginWithPassword: "पासवर्ड से लॉगिन करें", alreadyHaveAccount: "पहले से खाता है? लॉगिन करें", needAccount: "खाता नहीं है? नया खाता बनाएँ", sendOtpAndRegister: "मोबाइल सत्यापित करें और खाता बनाएँ", registerSuccess: "खाता सफलतापूर्वक बन गया। आप लॉगिन हो चुके हैं।",
    preferences: "आपकी बाज़ार प्राथमिकताएँ।", preferencesIntro: "ये प्राथमिकताएँ आपके खाते से ली गई हैं और लाइव बाज़ार निर्णय को आपके अनुसार बनाती हैं।", homeMandi: "मुख्य मंडी", preferredCrop: "पसंदीदा फसल", savePreferences: "प्राथमिकताएँ सहेजें", signInProfile: "प्रोफ़ाइल देखने के लिए साइन इन करें", loadingProfile: "प्रोफ़ाइल लोड हो रही है", profileLoadingMessage: "लाइव सेवा से आपकी सहेजी प्राथमिकताएँ ली जा रही हैं।", couldNotSavePreferences: "आपकी प्राथमिकताएँ सहेजी नहीं जा सकीं।", signOut: "साइन आउट", saveSuccess: "आपकी प्राथमिकताएँ सहेज दी गई हैं।",
    noLiveService: "लाइव सेवा तक पहुँचा नहीं जा सका।", connectionTryAgain: "कृपया कनेक्शन जाँचकर फिर कोशिश करें।", signedInMessage: "आप साइन इन हैं। जारी रखने के लिए बाज़ार दृश्य पर लौटें।", accountReadyMessage: "आपका किसान खाता तैयार है। आगे बढ़ने के लिए बाज़ार दृश्य पर लौटें।", otpRequested: "OTP का अनुरोध किया गया। अपने मोबाइल पर भेजा गया कोड दर्ज करें।", otpSignedIn: "आप OTP से साइन इन हैं। जारी रखने के लिए बाज़ार दृश्य पर लौटें।", alertsLoading: "आपकी अलर्ट सदस्यताएँ लोड हो रही हैं…", alertsLoadFailed: "आपकी अलर्ट सदस्यताएँ लोड नहीं हो सकीं।", retryAlerts: "अलर्ट फिर लोड करें", profileRetry: "प्रोफ़ाइल फिर लोड करें", voiceUnavailable: "इस ब्राउज़र में आवाज़ वाली सलाह उपलब्ध नहीं है।", voiceFailed: "आवाज़ वाली सलाह शुरू नहीं हो सकी।", trustTransparent: "पारदर्शी कीमत सीमा", trustLiveBackend: "लाइव बैकएंड डेटा", trustFarmerFirst: "किसान-प्रथम सलाह", invalidSelection: "कृपया सही फसल और मंडी चुनकर फिर कोशिश करें।", serviceUnavailable: "यह लाइव सेवा अस्थायी रूप से उपलब्ध नहीं है। कृपया थोड़ी देर बाद फिर कोशिश करें।", serviceTrouble: "लाइव सेवा में समस्या आ रही है। कृपया बाद में फिर कोशिश करें।", serviceCouldNotLoad: "आपके चयन के लिए यह जानकारी लोड नहीं हो सकी। कृपया फिर कोशिश करें।", serviceUnavailableTitle: "लाइव सेवा अस्थायी रूप से उपलब्ध नहीं", serviceCouldNotLoadTitle: "लाइव जानकारी लोड नहीं हो सकी", chooseCropMandiAlert: "अलर्ट सहेजने से पहले फसल और मंडी चुनें।", addMobileAlert: "अलर्ट सहेजने से पहले अपनी प्रोफ़ाइल में मोबाइल नंबर जोड़ें।", chooseDeliveryTime: "अलर्ट का समय चुनें।", enterTelegramChatId: "Telegram अलर्ट चालू करने के लिए chat ID दर्ज करें।", alertSaved: "आपकी अलर्ट सदस्यता सहेज दी गई है।", alertRemoved: "अलर्ट सदस्यता हटा दी गई है।", alertSaveFailed: "अलर्ट सदस्यता सहेजी नहीं जा सकी।", alertRemoveFailed: "अलर्ट सदस्यता हटाई नहीं जा सकी।",     chooseCropTitle: "फसल और मंडी चुनें", chooseCropDescription: "आलू, प्याज या टमाटर जैसी फसल चुनें और अपनी नज़दीकी मंडी चुनें।", seePricesTitle: "अगले 7 दिन के भाव देखें", seePricesDescription: "जानें किस दिन भाव सबसे अधिक रहेगा ताकि आप बेचने का समय तय कर सकें।", getAdviceTitle: "आज बेचें या रुकें?", getAdviceDescription: "बेचने का सही समय और बेहतर भाव देने वाली नज़दीकी मंडी की स्पष्ट सलाह पाएँ।",
    onboardingTitle: "3 आसान कदमों में अपनी फसल का सबसे अच्छा भाव पाएँ", onboardingIntro: "ऊपर अपनी फसल और नज़दीकी मंडी चुनें — हम आपको बताएँगे कि कब और कहाँ बेचना सबसे फायदेमंद है।", signupIntro: "लाइव मंडी भाव, मूल्य पूर्वानुमान और व्यक्तिगत अलर्ट पाने के लिए पंजीकरण करें।", editNumber: "नंबर बदलें", editDetails: "बदलें", showPassword: "पासवर्ड दिखाएँ", hidePassword: "पासवर्ड छिपाएँ", resendOtp: "OTP फिर भेजें", resendOtpIn: "OTP फिर भेजें", verifyAndCompleteSignup: "सत्यापित करें और खाता बनाएँ", telegramChatId: "Telegram चैट ID", alertLanguage: "अलर्ट भाषा", confirmRemoveAlert: "क्या आप यह अलर्ट सदस्यता हटाना चाहते हैं?", unusualPriceMovement: "असामान्य भाव बदलाव", warningsFound: "चेतावनियाँ मिलीं", recentPriceChange: "हाल का भाव बदलाव", bestDay: "सबसे अच्छा दिन", refreshAll: "फिर लोड करें",
    switchTheme: "रंग थीम बदलें", lightMode: "हल्की", darkMode: "गहरी", degraded: "सीमित", signInForRisk: "इस फसल और मंडी के लाइव आपूर्ति-जोखिम चेतावनियाँ देखने के लिए साइन इन करें।", signInForMandi: "नज़दीकी मंडी कीमतों की तुलना और श्रेष्ठ बिक्री बाज़ार देखने के लिए साइन इन करें।", latestMovementUnit: "₹ / क्विंटल / दिन", redirectingHome: "आप साइन इन हैं। बाज़ार दृश्य पर ले जाया जा रहा है…", passwordRequired: "कृपया कम से कम 6 अक्षरों का पासवर्ड बनाएँ।", otpWait: "सेकंड", singleDayOutlook: "एक दिन का अनुमान", notFoundTitle: "यह पृष्ठ उपलब्ध नहीं है", notFoundMessage: "जिस पृष्ठ को आप ढूँढ रहे हैं वह मौजूद नहीं है। जारी रखने के लिए लाइव बाज़ार दृश्य पर लौटें।", goHome: "बाज़ार दृश्य पर जाएँ", footerTagline: "किसानों और व्यापारियों के लिए लाइव APMC बाज़ार जानकारी।", whatsappChannel: "WhatsApp", telegramChannel: "Telegram", bothChannels: "WhatsApp और Telegram", siteNav: "साइट", mobileNav: "मोबाइल", themeGroup: "दिखावट", signedInAs: "साइन इन",
  },
} as const;

const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = "croplens_language";

export function LanguageProvider({ children, initialLanguage }: { children: ReactNode; initialLanguage?: Language }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (initialLanguage) return initialLanguage;
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored === "hi" ? "hi" : "en";
  });

  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(STORAGE_KEY, next);
  }, []);

  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
