import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: "en", label: "English (en)" },
  { code: "hi", label: "हिन्दी (hi)" },
  { code: "mr", label: "मराठी (mr)" },
  { code: "kn", label: "ಕನ್ನಡ (kn)" },
  { code: "te", label: "తెలుగు (te)" },
  { code: "ta", label: "தமிழ் (ta)" },
  { code: "gu", label: "ગુજરાતી (gu)" },
  { code: "bn", label: "বাংলা (bn)" },
  { code: "pa", label: "ਪੰਜਾਬੀ (pa)" },
];

const COMMON_AUTH_KEYS = {
  en: {
    "ticker.live": "Live Mandi Prices",
    "brand.tagline": "Know the market before the market moves.",
    "hero.title1": "AI-Powered Market",
    "hero.title2": "Intelligence for",
    "hero.title3": "Farmers & Traders",
    "hero.subtitle": "Know when to sell. Know where to sell. Know what comes next.",
    "snapshot.title": "Live Market Snapshot",
    "snapshot.live": "Live",
    "snapshot.perQuintal": "/ quintal",
    "snapshot.forecast": "7 Day Forecast",
    "advisory.listen": "Listen to Advisory (Voice Audio)",
    "advisory.playing": "Playing Advisory (Voice Audio)",
    "feature.forecast.title": "Price Forecasting",
    "feature.forecast.desc": "Accurate predictions",
    "feature.alerts.title": "Supply Shock Alerts",
    "feature.alerts.desc": "Stay ahead of risks",
    "feature.mandi.title": "Best Mandi Insights",
    "feature.mandi.desc": "Sell at the best rate",
    "feature.procurement.title": "Procurement Intelligence",
    "feature.procurement.desc": "For buyers & traders",
    "trust.secure": "Secure",
    "trust.trusted": "Trusted",
    "trust.built": "Built for Farmers",
    "trust.made": "Empowering Indian Farmers & Agri-Traders Nationwide 🇮🇳",
    "lang.label": "Language / भाषा",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.welcome": "Welcome Back! 👋",
    "auth.welcomeSub": "Login to access your CropLens AI dashboard",
    "auth.createTitle": "Create your account",
    "auth.createSub": "Join CropLens AI and trade smarter",
    "auth.methodPassword": "Mobile & Password",
    "auth.methodOtp": "Login with OTP",
    "auth.mobile": "Mobile Number",
    "auth.mobilePlaceholder": "Enter your mobile number",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.remember": "Remember me",
    "auth.forgot": "Forgot Password?",
    "auth.loginCta": "Login",
    "auth.continue": "or continue with",
    "auth.google": "Google Login",
    "auth.guest": "Guest Access",
    "auth.demoPresets": "Demo Presets (1-Click Access)",
    "auth.demoFarmer": "Demo as Farmer",
    "auth.demoFarmerSub": "Agra Potato Farmer",
    "auth.demoFarmerMode": "(Kisan Advisory Mode)",
    "auth.demoTrader": "Demo as Trader",
    "auth.demoTraderSub": "Azadpur Procurement Officer",
    "auth.demoTraderMode": "(Analytics Dashboard Mode)",
    "auth.safeTitle": "Your data is safe with us",
    "auth.safeSub": "Industry-standard encryption to protect your information",
    "auth.otpSend": "Send OTP",
    "auth.otpVerify": "Verify & Login",
    "auth.otpLabel": "One-Time Password",

    // Farmer Mode
    "farmer.greeting": "Welcome",
    "farmer.demoName": "Kisan Mitra",
    "farmer.mandiLabel": "APMC (Mandi)",
    "farmer.selectCrop": "Select Crop",
    "farmer.selectMandi": "Select Mandi",
    "farmer.selectLang": "Language",
    "farmer.decision.advice": "ADVICE",
    "farmer.decision.riseNotice": "Prices are expected to rise in",
    "farmer.confidence": "Forecast Accuracy",
    "farmer.highAccuracy": "High Accuracy",
    "farmer.audio.title": "30-Second Kisan Advisory (Voice Audio)",
    "farmer.audio.speed": "Playback Speed",
    "farmer.audio.badge": "Voice Advisory",
    "farmer.table.title": "Where Should You Sell?",
    "farmer.table.subtitle": "(Net Profit After Transport)",
    "farmer.table.mandi": "Mandi Name",
    "farmer.table.distance": "Distance (km)",
    "farmer.table.rate": "Market Rate (₹/Quintal)",
    "farmer.table.transport": "Est. Transport Cost (₹/Quintal)",
    "farmer.table.profit": "Net Profit / Quintal (₹)",
    "farmer.table.rec": "Recommendation",
    "farmer.chart.title": "7-Day Price Forecast",
    "farmer.chart.rise": "Expected Rise",
    "farmer.chart.drop": "Possible Drop",
    "farmer.chart.peak": "Peak Price",
    "farmer.nav.dashboard": "Dashboard",
    "farmer.nav.advisory": "Today's Advisory",
    "farmer.nav.forecast": "Price Forecast",
    "farmer.nav.mandi": "Mandi Comparison",
    "farmer.nav.news": "Market News",
    "farmer.nav.alerts": "Alerts",
    "farmer.nav.profile": "My Profile",
    "farmer.nav.activity": "My Activity",
    "farmer.nav.settings": "Settings",
    "farmer.nav.help": "Help Center",
    "farmer.help.title": "Need Help?",
    "farmer.help.call": "Call us:"
  },
  hi: {
    "trust.made": "देशभर में भारतीय किसानों और कृषि-व्यापारियों को सशक्त बनाना 🇮🇳",
    "ticker.live": "लाइव मंडी भाव",
    "brand.tagline": "बाज़ार की चाल से पहले जानें बाज़ार का रुख।",
    "hero.title1": "किसान और व्यापारी के लिए",
    "hero.title2": "इंटेलिजेंट",
    "hero.title3": "मंडी इंटेलिजेंस",
    "hero.subtitle": "बेहतर फ़ैसले। सही दाम। मज़बूत किसान।",
    "snapshot.title": "लाइव मंडी झलक",
    "snapshot.live": "लाइव",
    "snapshot.perQuintal": "/ क्विंटल",
    "snapshot.forecast": "7 दिवसीय अनुमान",
    "advisory.listen": "सलाह सुनें (ऑडियो)",
    "advisory.playing": "सलाह चल रही है (ऑडियो)",
    "feature.forecast.title": "मूल्य पूर्वानुमान",
    "feature.forecast.desc": "सटीक अनुमान",
    "feature.alerts.title": "सप्लाई शॉक अलर्ट",
    "feature.alerts.desc": "जोखिम से आगे रहें",
    "feature.mandi.title": "सर्वश्रेष्ठ मंडी जानकारी",
    "feature.mandi.desc": "सही दाम पर बेचें",
    "feature.procurement.title": "खरीद इंटेलिजेंस",
    "feature.procurement.desc": "व्यापारियों के लिए",
    "trust.secure": "सुरक्षित",
    "trust.trusted": "विश्वसनीय",
    "trust.built": "किसानों के लिए निर्मित",
    "lang.label": "भाषा / Language",
    "auth.login": "लॉगिन करें",
    "auth.signup": "रजिस्टर करें",
    "auth.welcome": "वापसी पर स्वागत है! 👋",
    "auth.welcomeSub": "अपने CropLens AI डैशबोर्ड में लॉगिन करें",
    "auth.createTitle": "नया खाता बनाएं",
    "auth.createSub": "CropLens AI से जुड़ें और समझदारी से व्यापार करें",
    "auth.methodPassword": "मोबाइल एवं पासवर्ड",
    "auth.methodOtp": "OTP से लॉगिन करें",
    "auth.mobile": "मोबाइल नंबर",
    "auth.mobilePlaceholder": "अपना 10-अंकों का नंबर दर्ज करें",
    "auth.password": "पासवर्ड",
    "auth.passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "auth.remember": "मुझे याद रखें",
    "auth.forgot": "पासवर्ड भूल गए?",
    "auth.loginCta": "लॉगिन करें →",
    "auth.continue": "या इनके साथ जारी रखें",
    "auth.google": "Google लॉगिन",
    "auth.guest": "गेस्ट प्रवेश",
    "auth.demoPresets": "डेमो निर्देश (1-क्लिक एक्सेस)",
    "auth.demoFarmer": "किसान डेमो",
    "auth.demoFarmerSub": "आगरा आलू किसान",
    "auth.demoFarmerMode": "(किसान सलाह मोड)",
    "auth.demoTrader": "व्यापारी डेमो",
    "auth.demoTraderSub": "आज़ादपुर खरीद अधिकारी",
    "auth.demoTraderMode": "(एनालिटिक्स डैशबोर्ड मोड)",
    "auth.safeTitle": "आपकी जानकारी पूर्ण सुरक्षित है",
    "auth.safeSub": "उद्योग-मानक एन्क्रिप्शन द्वारा सुरक्षित",
    "auth.otpSend": "OTP भेजें",
    "auth.otpVerify": "सत्यापित करें और लॉगिन करें",
    "auth.otpLabel": "एक-बार का पासवर्ड (OTP)",

    // Farmer Mode (Hindi)
    "farmer.greeting": "नमस्ते",
    "farmer.demoName": "किसान मित्र",
    "farmer.mandiLabel": "मंडी",
    "farmer.selectCrop": "फसल चुनें",
    "farmer.selectMandi": "मंडी चुनें",
    "farmer.selectLang": "भाषा चुनें",
    "farmer.decision.advice": "सलाह",
    "farmer.decision.riseNotice": "मंडी में भाव बढ़ने की संभावना है:",
    "farmer.confidence": "पूर्वानुमान सटीकता",
    "farmer.highAccuracy": "उच्च सटीकता",
    "farmer.audio.title": "30-सेकंड कृषि सलाह (ऑडियो)",
    "farmer.audio.speed": "बोलने की गति",
    "farmer.audio.badge": "ऑडियो सलाह",
    "farmer.table.title": "अपनी फसल कहाँ बेचें?",
    "farmer.table.subtitle": "(परिवहन खर्च के बाद शुद्ध मुनाफा)",
    "farmer.table.mandi": "मंडी का नाम",
    "farmer.table.distance": "दूरी (किमी)",
    "farmer.table.rate": "मंडी भाव (₹/क्विंटल)",
    "farmer.table.transport": "अनुमानित परिवहन खर्च (₹/क्विंटल)",
    "farmer.table.profit": "शुद्ध मुनाफा / क्विंटल (₹)",
    "farmer.table.rec": "सलाह",
    "farmer.chart.title": "7-दिवसीय मूल्य पूर्वानुमान",
    "farmer.chart.rise": "संभावित बढ़ोतरी",
    "farmer.chart.drop": "संभावित गिरावट",
    "farmer.chart.peak": "उच्चतम भाव",
    "farmer.nav.dashboard": "डैशबोर्ड",
    "farmer.nav.advisory": "आज की सलाह",
    "farmer.nav.forecast": "मूल्य पूर्वानुमान",
    "farmer.nav.mandi": "मंडी तुलना",
    "farmer.nav.news": "कृषि समाचार",
    "farmer.nav.alerts": "अलर्ट",
    "farmer.nav.profile": "मेरी प्रोफाइल",
    "farmer.nav.activity": "मेरी गतिविधियाँ",
    "farmer.nav.settings": "सेटिंग्स",
    "farmer.nav.help": "सहायता केंद्र",
    "farmer.help.title": "सहायता चाहिए?",
    "farmer.help.call": "संपर्क करें:"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('croplens_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('croplens_lang', lang);
  }, [lang]);

  const t = (key) => {
    const dict = COMMON_AUTH_KEYS[lang] || COMMON_AUTH_KEYS['en'];
    return dict[key] || COMMON_AUTH_KEYS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
