"""Add MarketData and WeatherData models for live sync

Revision ID: ca5c9b8af625
Revises: 001_initial
Create Date: 2026-08-21 13:30:33.773589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5c9b8af625'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('arrivals_in_qtl', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_commodity'), 'market_data', ['commodity'], unique=False)
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_market'), 'market_data', ['market'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_date'), 'weather_data', ['date'], unique=False)
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_market'), 'weather_data', ['market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_market'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_date'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_market_data_market'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_commodity'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
